// Mocks generated by Mockito 5.4.6 from annotations
// in byte_beam/test/features/vehicle_detail/presentation/bloc/vehicle_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:byte_beam/features/alerts/domain/alert_persistence.dart' as _i5;
import 'package:byte_beam/features/alerts/domain/entities/alert.dart' as _i6;
import 'package:byte_beam/features/fleet/domain/entities/vehicle.dart' as _i4;
import 'package:byte_beam/features/fleet/domain/repositories/fleet_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FleetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFleetRepository extends _i1.Mock implements _i2.FleetRepository {
  MockFleetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Vehicle>> watchFleet() =>
      (super.noSuchMethod(
            Invocation.method(#watchFleet, []),
            returnValue: _i3.Stream<List<_i4.Vehicle>>.empty(),
          )
          as _i3.Stream<List<_i4.Vehicle>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AlertPersistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertPersistence extends _i1.Mock implements _i5.AlertPersistence {
  MockAlertPersistence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveDismissed(_i6.Alert? alert, _i6.DismissReason? reason) =>
      (super.noSuchMethod(
            Invocation.method(#saveDismissed, [alert, reason]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Alert>> loadDismissed() =>
      (super.noSuchMethod(
            Invocation.method(#loadDismissed, []),
            returnValue: _i3.Future<List<_i6.Alert>>.value(<_i6.Alert>[]),
          )
          as _i3.Future<List<_i6.Alert>>);
}
